version: '3.3'
services:
  graylog-mongo:
    container_name: standalone.mongodb.graylog
    hostname: standalone.mongodb.graylog
    image: mongo:3
    networks:
      graylog_stack_network:
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  graylog-elasticsearch:
    cap_add:
      - IPC_LOCK
    container_name: standalone.elasticsearch.graylog
    environment:
      ES_JAVA_OPTS: ${ES_JAVA_OPTS:--Xms5120m -Xmx5120m}
    hostname: standalone.elasticsearch.graylog
    image: cirepo/elasticsearch:6.8.6
#    mem_limit: ${MEM_LIMIT:-10g}
    networks:
      graylog_stack_network:
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_log:/var/log/elasticsearch
  graylog:
    container_name: standalone.graylog
    environment:
      - GRAYLOG_ELASTICSEARCH_HOSTS=${GRAYLOG_ELASTICSEARCH_HOSTS:-http://standalone.elasticsearch.graylog:9200}
      #- GRAYLOG_ELASTICSEARCH_CLUSTER_NAME=${GRAYLOG_ELASTICSEARCH_CLUSTER_NAME:-standalone.elasticsearch.graylog}
      - GRAYLOG_MONGODB_URI=${GRAYLOG_MONGODB_URI:-mongodb://standalone.mongodb.graylog/graylog}
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET:-somepasswordpepper}
      - GRAYLOG_HTTP_ENABLE_CORS=${GRAYLOG_REST_ENABLE_CORS:-true}
      - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI:-http://127.0.0.1:9000/}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2:-8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918}
      # Generate your own password with this command:
      # OSX
      # echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | shasum -a 256 | cut -d" " -f1
      # linux
      # echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1

      #- GRAYLOG_TRANSPORT_EMAIL_ENABLED=true
      #- GRAYLOG_TRANSPORT_EMAIL_HOSTNAME=smtp
      #- GRAYLOG_TRANSPORT_EMAIL_PORT=25
      #- GRAYLOG_TRANSPORT_EMAIL_USE_AUTH=false
      #- GRAYLOG_TRANSPORT_EMAIL_USE_TLS=false
      #- GRAYLOG_TRANSPORT_EMAIL_USE_SSL=false

      #- GRAYLOG_WEB_ENABLE_CORS=${GRAYLOG_WEB_ENABLE_CORS:-true}
      #- GRAYLOG_WEB_ENDPOINT_URI=${GRAYLOG_WEB_ENDPOINT_URI:-http://127.0.0.1:9000/api}
    hostname: standalone.graylog
    image: graylog/graylog:3.2
    networks:
      graylog_stack_network:
    ports:
      # Graylog web interface and REST API
      - ${EXTERNAL_GRAYLOG_REST_9000_PORT:-9000}:9000
      # GELF TCP/UDP
      - ${EXTERNAL_GRAYLOG_GELF_12201_PORT:-12201}:12201
      - ${EXTERNAL_GRAYLOG_GELF_12201_PORT:-12201}:12201/udp
      # Syslog TCP/UDP
      - ${EXTERNAL_GRAYLOG_SYSLOG_514_PORT:-514}:514
      - ${EXTERNAL_GRAYLOG_SYSLOG_514_PORT:-514}:514/udp
    restart: always
    volumes:
      - ./data/usr/share/graylog/data/config:/usr/share/graylog/data/config:rw
      - graylog_journal:/usr/share/graylog/data/journal

networks:
  graylog_stack_network:
    driver: overlay

volumes:
  elasticsearch_data:
    driver: local
  elasticsearch_log:
    driver: local
  graylog_journal:
    driver: local
  mongo_db:
    driver: local
